climate_transforms:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('REGION') }}"
      priority: interactive
      retries: 3
      keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"s